### ISSUE TITLE
What's the process of participating phase 2 ceremony of the next release?

### ISSUE THREAD

**Issue by Chengxuan** [iden3/phase2ceremony#1]
Hi Iden3 team, @OBrezhniev mentioned in https://github.com/kaleido-io/kaleido-iden3-samples/issues/17#issuecomment-1383283274 that there will be opportunities for participating in the phase 2 ceremony. Can you share the process and required setup for participation?

**Comment by OBrezhniev** [comment]
Hi @Chengxuan! We have started the setup. Ping me in discord or by email, and I will guide you through.
You will need the latest [snarkjs](https://github.com/iden3/snarkjs) to do a contribution and [keybase](https://keybase.io/) to sign your contribution report.
